### ISSUE TITLE
SyntaxError when importing flexboxgrid.css

### ISSUE THREAD

**Issue by pbojinov** [roylee0704/react-flexbox-grid#28]
Hey guys, first of all I wanted to say thanks for this project. It looks awesome and I'm excited to use it!

But I'm having some trouble with the integration. When I run the local webpack server I'm getting a syntax error on the imported `flexboxgrid.css`.

```
/Users/petarbojinov/frostytechnologies/frosty-starter/node_modules/flexboxgrid/dist/flexboxgrid.css:1
(function (exports, require, module, __filename, __dirname) { .container-fluid,
                                                              ^

SyntaxError: Unexpected token .
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Module._extensions..js (module.js:442:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/petarbojinov/frostytechnologies/frosty-starter/node_modules/babel-core/node_modules/babel-register/lib/node.js:134:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/petarbojinov/frostytechnologies/frosty-starter/node_modules/react-flexbox-grid/lib/components/Grid.js:13:20)
    at Module._compile (module.js:435:26)
    at Module._extensions..js (module.js:442:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/petarbojinov/frostytechnologies/frosty-starter/node_modules/babel-core/node_modules/babel-register/lib/node.js:134:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)

```

Here's my webpack config: https://gist.github.com/pbojinov/e87fb7aaf497faf14057
and I started with this boilerplate project: https://github.com/DominicTobias/universal-react

Also made sure to install `classnames & flexboxgrid`. And I tried the alternative webpack config options in the readme. Any suggestions would be great, thanks!

**Comment by silvenon** [comment]
Update react-flexbox-grid to the latest version and replace your first loader with the first loader in our webpack configuration docs.

**Comment by pbojinov** [comment]
@silvenon I did a force update on react-flexbox-grid to the latest `npm install react-flexbox-grid@0.9.5` and updated the filter loader to use the first loader from the docs, but still getting the same error.

To reproduce this, here's a clean boilerplate app with `react-flexbox-grid` installed and the webpack config configured as per the docs. At first I thought it was because `style-loader and css-loader` were missing but those are installed as well.

**Comment by roylee0704** [comment]
contrib to doc #26

**Comment by silvenon** [comment]
@pbojinov found it! Webpack itself doesn't cause this error (`npm run build` works fine), your `server.js` does. It does `require('./app')`, which requires `react-flexbox-grid`, which ultimately requires `flexboxgrid.css`. This causes an error because Node tries to parse `flexboxgrid.css` like JS. You should find a different way to achieve whatever that `require` does.

**Comment by pbojinov** [comment]
@silvenon that makes perfect sense! Good catch, I'll try tweaking the webpack configs to handle that case with some excludes/includes

**Comment by silvenon** [comment]
Great, closing this then :+1:

**Comment by pbojinov** [comment]
I found out what the issue was...since the boilerplate is isomorphic, babel tries to parse a CSS file even though proper loaders are defined in the `webpack.config.js.`

A [workaround](https://github.com/webpack/webpack/issues/1754#issuecomment-186856033) is the add this to the top of your dev and production webpack configs and it will build fine!
```
require.extensions['.css'] = () => {
  return;
};
```

**Comment by silvenon** [comment]
Just to be clear, [`require.extensions`](https://nodejs.org/api/globals.html#globals_require_extensions) is a Node feature. Wepback is loading this CSS file just fine, but Node isn't (from `server.js`), so here you are disabling loading CSS files, which is fine. Do classes print out fine, though?

**Comment by shiroganee** [comment]
Hello, got identical error (I'm running isomorphic application as well). You've got the solution maybe @pbojinov ? Cause I tried to use that 
```
require.extensions['.css'] = () => {
  return;
};
```

and it didn't work at all

**Comment by silvenon** [comment]
@shiroganee which Node version are you using?

**Comment by shiroganee** [comment]
@silvenon 5.8 right now.

**Comment by silvenon** [comment]
The docs say that the feature has been deprecated, I'm not sure what that means exactly. Maybe @shiroganee is using an older version of Node where this worked?

Try moving the `require.extensions` part to `server.js`.

**Comment by petermikitsh** [comment]
Anyone have a solution for those of us who aren't building our server code with webpack? Universal apps don't like when you try and import css files server-side.

**Comment by silvenon** [comment]
@petermikitsh are you using some other module bundler?

**Comment by petermikitsh** [comment]
@silvenon Sorry, let me elaborate further: I bundle my client side assets with webpack. I'm using babel-register for ES6 functionality for my server side code, but otherwise, I just run my app using `node server.js`. My app is a universal React-Redux app, so I render the initial page load on the server. When importing this package in one of my React components, the server-side code trips up on `require`ing a file with a `css` extension. I assume it's trying to parse it as javascript.

**Comment by silvenon** [comment]
@petermikitsh oh, I'm not familiar with that workflow, too bad you can't compile it before running it on the server… Requiring CSS, images etc. is really common when using webpack.

**Comment by petermikitsh** [comment]
I agree, these files are really common to require, when you are on the _client_. I bundle my css and js for the client specifically, and then reference them in my initial HTML payload. If this package code didn't explicitly import the css for you, and you had to add a line of code to do it yourself, it would be more flexible for my use case. I'm not particularly opposed to compiling my server-side code, I just don't see much value in doing so, unless its to support use cases like this.

**Comment by haovn577** [comment]
Try all cases, still get this error.
Boilerplate: https://github.com/erikras/react-redux-universal-hot-example

**Comment by silvenon** [comment]
@petermikitsh then you wouldn't be able to load it with CSS Modules :confused: Perhaps we could make a build already compiled with webpack, @roylee0704?

**Comment by petermikitsh** [comment]
The most elegant solution would be to require package users to require the css files themselves. My entry point in my client-side code calls `require`, as outlined in [react-flexgrid's documentation](https://github.com/nkt/react-flexgrid/blame/master/README.md#L16).

I don't see why a compiled version wouldn't work. Run `babel` in a `prepublish` npm hook.

**Comment by silvenon** [comment]
@petermikitsh simply requiring the CSS file yourself won't give you the benefit of CSS Modules. This is already built with Babel, but there should definitely also be a completely compiled build, for people who don't use webpack.

**Comment by silvenon** [comment]
```js
extensions: ['.less','.scss','.css'],
```

**Comment by silvenon** [comment]
Also, you need other extensions as well. This will *overwrite* the existing ones, not append to them. You need to add back `.js`, `webpack.js` and whatever the default ones where.

**Comment by rsteckler** [comment]
I only appended .css.  The others already existed.  [Here's the original](https://github.com/erikras/react-redux-universal-hot-example/blob/master/webpack/webpack-isomorphic-tools.js#L65).

**Comment by silvenon** [comment]
@rsteckler my bad. So it worked for you? There's no issue? I misunderstood your comment then :+1:

**Comment by rsteckler** [comment]
Sorry I wasn't clear.  It's now working for me in dev and prod builds :)

**Comment by SpainTrain** [comment]
I was having this issue and solved it like so in server webpack config:

- use `css-loader/locals` (or just `css/locals`) as described here - https://github.com/webpack/css-loader/issues/59#issuecomment-109793167
- ensure that `flexboxgrid` and `react-flexbox-grid` are not in webpack `externals`

**Comment by mrsufgi** [comment]
@rsteckler I'm also using universal hot but it can't get it to work in prod (only in dev) 
can u share you prod.config and dev.config as well as the webpack isomorphic?

**Comment by jhabdas** [comment]
@pbojinov's solution got me past the compile failure. then I get some other errors:

```
Error in ./~/react-flexbox-grid/lib/components/Grid.js
Module not found: Error: Cannot resolve module 'style' in /Users/jhabdas/Developer/11trails/node_modules/react-flexbox-grid/lib/components
 @ ./~/react-flexbox-grid/lib/components/Grid.js 18:19-41

Error in ./~/react-flexbox-grid/lib/components/Col.js
Module not found: Error: Cannot resolve module 'style' in /Users/jhabdas/Developer/11trails/node_modules/react-flexbox-grid/lib/components
 @ ./~/react-flexbox-grid/lib/components/Col.js 14:19-41

Error in ./~/react-flexbox-grid/lib/components/Row.js
Module not found: Error: Cannot resolve module 'style' in /Users/jhabdas/Developer/11trails/node_modules/react-flexbox-grid/lib/components
 @ ./~/react-flexbox-grid/lib/components/Row.js 18:19-41
```

```
├── flexboxgrid@6.3.1
├── react-flexbox-grid@0.10.2
```

I feel so dirty.

**Comment by silvenon** [comment]
@jhabdas can you paste your webpack config?

**Comment by silvenon** [comment]
@mrsufgi you too, if you still have issues.

**Comment by jhabdas** [comment]
Configs can be found here, @silvenon: https://github.com/jaredpalmer/react-production-starter/tree/master/tools. Thank you kindly for any help you can provide.

**Comment by mschipperheyn** [comment]
@jhabas if you ignore the css as you do in the server config, I assume the the style object, that classNames.js tries to import as an object reference, will be undefined and lead to an error.

**Comment by mschipperheyn** [comment]
In other news, if you use https://github.com/LoicMahieu/react-styled-flexboxgrid instead, you're using styled components, bypassing the whole nightmare

**Comment by ranneyd** [comment]
Just a heads up, using browserify results in similar issues. It goes down the chain and tries to import the css as js. You should consider reworking how the css works to be friendlier to other build systems.

**Comment by silvenon** [comment]
@ranneyd the next version (will be releasing soon) will not require CSS Modules. I haven't tried it, but the only thing you will need to make it work with browserify is something like [cssify](https://github.com/davidguttman/cssify).

**Comment by jhabdas** [comment]
I imagine there are some tradeoffs being made to drop CSS modules? FWIW having a lib targeted at CSS modules is why I started using this in the first place. I'd rather have a couple of sharp, purpose made tools than a Swiss Army knife. But that's just me.

**Comment by silvenon** [comment]
@jhabdas we will still support CSS Modules like before, but in case they aren't configured, react-flexbox-grid will fall back to regular classes.

Personally I think that CSS Modules are a bit of an overkill for this library, so now we'll finally have a release which doesn't require them.

Let me know if I misunderstood what you meant. 😉

**Comment by palavrov** [comment]
Got the same error.
My fix was to use https://github.com/knpwrs/css-modules-electron

**Comment by danny-andrews** [comment]
I believe the right solution for this is to distribute a pre-built version of this library. Consumers of a library shouldn't have to add special config options to their build process just to use them. The distributed version of the library should be compatible with its targeted environment.

**Comment by jhabdas** [comment]
> Consumers of a library shouldn't have to add special config options to their build process just to use them.

Following that logic. Why would one need a build process anyway?

**Comment by danny-andrews** [comment]
Uh, to build your own files, not your dependencies.

**Comment by slavab89** [comment]
This is the solution that i've used and it seems to have worked

For the client rules:
```js
{
  test: /\.css$/,
  loader: 'style-loader!css-loader?modules',
  include: /flexboxgrid/
},
{
  test: /\.css$/,
  use: "WHATEVER_LOADER",
  include: /src/myapp/css,
  exclude: /flexboxgrid/
}
```

For the server rules:
```js
{
  test: /\.css$/,
  loader: ExtractTextPlugin.extract({
    fallback: "style-loader",
    use: "css-loader?modules"
  }),
  include: /flexboxgrid/
},
{
  test: /\.css$/,
  use: "WHATEVER_LOADER",
  include: /src/myapp/css,
  exclude: /flexboxgrid/
}
```
And the plugin (server):
```JS
new ExtractTextPlugin('styles/flexboxgrid.css'),
```

For production, you should probably use the `ExtractTextPlugin` for the client side as well.

**Comment by roylee0704** [comment]
It should be fixed under v1.1.4 now

**Comment by mschipperheyn** [comment]
I still have the error. Are there any remaining requirements to be satisfied for the fix to work?

**Comment by danny-andrews** [comment]
@mschipperheyn Which version are you using?

**Comment by danny-andrews** [comment]
In v1.1.5, you have to use the isomorphic build (located under `react-flexbox-grid/dist`). This version prebuilds the css and extracts it into a separate file, `react-flexbox-grid.css`. You will have to include this into your css bundle manually.

https://github.com/roylee0704/react-flexbox-grid#isomorphic-support

**Comment by MaximusDesign** [comment]
We also encounter this error. A fix would be appreciated.

**Comment by danny-andrews** [comment]
@MaximusDesign Have you tried any of the solutions listed [above](https://github.com/roylee0704/react-flexbox-grid/issues/28#issuecomment-325825260)?

**Comment by stephane-r** [comment]
Same error on Create React App :(

**Comment by shahafan** [comment]
I have found a nice solution for server side rendered apps.

So, i was trying to go with @pbojinov answer and implemented `require.extensions['.css'] = () => {};` on the server.

It was partially working.. the app was running but the classes were different while loading the app from server / client side.

So for example on the server side i've got class="col-xs-6" while on the client I got class="flexboxgrid2__col-xs-6___3JeAf" .

That wasn't good enough.. I kept looking for a better way to compile the classes on the server and found css-modules-require-hook module which worked like a charm!

```
require('css-modules-require-hook')({
    generateScopedName: '[name]__[local]___[hash:base64:5]',
    extensions        : ['.scss', '.css'],
    camelCase         : 'dashes',
});
```

@roylee0704 I think this should be on the doc.

BTW, the framework I'm working with is nextjs, but this will work on any server rendered environment.

**Comment by axeen** [comment]
I had this issue as well, and after days of trying different solutions without luck, I found a module called `next-transpile-modules` that solved it!

Like so:
```
const withSass = require('@zeit/next-sass');
const withCSS = require('@zeit/next-css');
const withTM = require('next-transpile-modules');

module.exports = withCSS(withSass(withTM({
  transpileModules: ['react-flexbox-grid']
})));
```
